version: '3'

services:
  boardgamevault:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app:ro
    environment:
      - DATABASE_URL=postgresql://postgres:ShibaInu@db/BoardGameVault
    ports:
      - "8000:8000"

  db:
      image: postgres:15-alpine
      volumes:
        - ./postgres/data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=ShibaInu
        - POSTGRES_DB=BoardGameVault
